# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\86131\Desktop\QT.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("background-image: url(:/S/322059.jpg);\n"
"font: 75 13pt \"Bahnschrift\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_4.addWidget(self.pushButton_10)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_4.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_4.addWidget(self.pushButton_12)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_5.addWidget(self.pushButton_20)
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_5.addWidget(self.pushButton_19)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_5.addWidget(self.pushButton_14)
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_5.addWidget(self.pushButton_13)
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_5.addWidget(self.pushButton_15)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_6.addWidget(self.pushButton_16)
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_6.addWidget(self.pushButton_18)
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_6.addWidget(self.pushButton_17)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLinkButton.sizePolicy().hasHeightForWidth())
        self.commandLinkButton.setSizePolicy(sizePolicy)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.horizontalLayout.addWidget(self.commandLinkButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_10.addWidget(self.pushButton_26)
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout_10.addWidget(self.pushButton_29)
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_10.addWidget(self.pushButton_25)
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_10.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_10.addWidget(self.pushButton_23)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_7.addWidget(self.pushButton_27)
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_7.addWidget(self.pushButton_21)
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_7.addWidget(self.pushButton_28)
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_7.addWidget(self.pushButton_24)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_14.addWidget(self.label_7)
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLinkButton_2.sizePolicy().hasHeightForWidth())
        self.commandLinkButton_2.setSizePolicy(sizePolicy)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.horizontalLayout_14.addWidget(self.commandLinkButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_37 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayout_8.addWidget(self.pushButton_37)
        self.pushButton_42 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_42.setObjectName("pushButton_42")
        self.horizontalLayout_8.addWidget(self.pushButton_42)
        self.pushButton_33 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_33.setObjectName("pushButton_33")
        self.horizontalLayout_8.addWidget(self.pushButton_33)
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_8.addWidget(self.pushButton_30)
        self.pushButton_36 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_8.addWidget(self.pushButton_36)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_38 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_38.setObjectName("pushButton_38")
        self.horizontalLayout_11.addWidget(self.pushButton_38)
        self.pushButton_32 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_32.setObjectName("pushButton_32")
        self.horizontalLayout_11.addWidget(self.pushButton_32)
        self.pushButton_40 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_40.setObjectName("pushButton_40")
        self.horizontalLayout_11.addWidget(self.pushButton_40)
        self.pushButton_43 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_43.setObjectName("pushButton_43")
        self.horizontalLayout_11.addWidget(self.pushButton_43)
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_31.setObjectName("pushButton_31")
        self.horizontalLayout_11.addWidget(self.pushButton_31)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_35 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_35.setObjectName("pushButton_35")
        self.horizontalLayout_12.addWidget(self.pushButton_35)
        self.pushButton_44 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_44.setObjectName("pushButton_44")
        self.horizontalLayout_12.addWidget(self.pushButton_44)
        self.pushButton_39 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_39.setObjectName("pushButton_39")
        self.horizontalLayout_12.addWidget(self.pushButton_39)
        self.pushButton_41 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_41.setObjectName("pushButton_41")
        self.horizontalLayout_12.addWidget(self.pushButton_41)
        self.pushButton_45 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_45.setObjectName("pushButton_45")
        self.horizontalLayout_12.addWidget(self.pushButton_45)
        self.pushButton_34 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_34.setObjectName("pushButton_34")
        self.horizontalLayout_12.addWidget(self.pushButton_34)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_15.addWidget(self.label_8)
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLinkButton_3.sizePolicy().hasHeightForWidth())
        self.commandLinkButton_3.setSizePolicy(sizePolicy)
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.horizontalLayout_15.addWidget(self.commandLinkButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_51 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_51.setObjectName("pushButton_51")
        self.horizontalLayout_13.addWidget(self.pushButton_51)
        self.pushButton_46 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_46.setObjectName("pushButton_46")
        self.horizontalLayout_13.addWidget(self.pushButton_46)
        self.pushButton_47 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_47.setObjectName("pushButton_47")
        self.horizontalLayout_13.addWidget(self.pushButton_47)
        self.pushButton_50 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_50.setObjectName("pushButton_50")
        self.horizontalLayout_13.addWidget(self.pushButton_50)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_49 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_49.setObjectName("pushButton_49")
        self.horizontalLayout_9.addWidget(self.pushButton_49)
        self.pushButton_54 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_54.setObjectName("pushButton_54")
        self.horizontalLayout_9.addWidget(self.pushButton_54)
        self.pushButton_52 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_52.setObjectName("pushButton_52")
        self.horizontalLayout_9.addWidget(self.pushButton_52)
        self.pushButton_48 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_48.setObjectName("pushButton_48")
        self.horizontalLayout_9.addWidget(self.pushButton_48)
        self.pushButton_53 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_53.setObjectName("pushButton_53")
        self.horizontalLayout_9.addWidget(self.pushButton_53)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 33))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.actionjdl = QtWidgets.QAction(MainWindow)
        self.actionjdl.setObjectName("actionjdl")
        self.actionlianxi = QtWidgets.QAction(MainWindow)
        self.actionlianxi.setObjectName("actionlianxi")
        self.menu.addAction(self.actionjdl)
        self.menu.addAction(self.actionlianxi)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QT控件"))
        self.label.setText(_translate("MainWindow", "界面布局Layouts"))
        self.pushButton_4.setText(_translate("MainWindow", "Form形式"))
        self.pushButton.setText(_translate("MainWindow", "Vertical垂直"))
        self.pushButton_2.setText(_translate("MainWindow", "Horizontal水平"))
        self.pushButton_3.setText(_translate("MainWindow", " Grid网格"))
        self.label_2.setText(_translate("MainWindow", "间距Spacers"))
        self.pushButton_6.setText(_translate("MainWindow", " Vertical垂直"))
        self.pushButton_5.setText(_translate("MainWindow", "Horizontal水平"))
        self.label_3.setText(_translate("MainWindow", "按钮Buttons"))
        self.pushButton_10.setText(_translate("MainWindow", "Check Box复选框"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton按钮"))
        self.pushButton_9.setText(_translate("MainWindow", "Radio广播"))
        self.pushButton_8.setText(_translate("MainWindow", "Tool工具"))
        self.pushButton_11.setText(_translate("MainWindow", "Command Link命令链接"))
        self.pushButton_12.setText(_translate("MainWindow", "Dialog Button Box对话框按钮盒"))
        self.label_4.setText(_translate("MainWindow", "单元视图ltem Views"))
        self.pushButton_20.setText(_translate("MainWindow", "Undo撤销"))
        self.pushButton_19.setText(_translate("MainWindow", "Column列"))
        self.pushButton_14.setText(_translate("MainWindow", "Tree树形"))
        self.pushButton_13.setText(_translate("MainWindow", "List列表"))
        self.pushButton_15.setText(_translate("MainWindow", "Table表格"))
        self.label_5.setText(_translate("MainWindow", "单元组件ltem Widgets"))
        self.pushButton_16.setText(_translate("MainWindow", "List列表"))
        self.pushButton_18.setText(_translate("MainWindow", "Table表格"))
        self.pushButton_17.setText(_translate("MainWindow", "Tree树形"))
        self.label_6.setText(_translate("MainWindow", "容器Containers"))
        self.commandLinkButton.setText(_translate("MainWindow", "容器精讲网址"))
        self.pushButton_26.setText(_translate("MainWindow", "Frame     框架"))
        self.pushButton_29.setText(_translate("MainWindow", " DockWidget     停靠窗口"))
        self.pushButton_25.setText(_translate("MainWindow", "StackedWidget    控件栈"))
        self.pushButton_22.setText(_translate("MainWindow", "ScrollArea     滚动区"))
        self.pushButton_23.setText(_translate("MainWindow", "ToolBox     工具箱"))
        self.pushButton_27.setText(_translate("MainWindow", " Widget     组件"))
        self.pushButton_21.setText(_translate("MainWindow", "GroupBox     组合框"))
        self.pushButton_28.setText(_translate("MainWindow", "MdiArea     MDI窗口显示区"))
        self.pushButton_24.setText(_translate("MainWindow", "TabWidget     切换卡"))
        self.label_7.setText(_translate("MainWindow", "输入组件InputWidgets"))
        self.commandLinkButton_2.setText(_translate("MainWindow", "输入组件精讲网址"))
        self.pushButton_37.setText(_translate("MainWindow", "Horizontal ScrollBar     水平滚动条"))
        self.pushButton_42.setText(_translate("MainWindow", "DoubleSpinBox     小数旋转框 "))
        self.pushButton_33.setText(_translate("MainWindow", "Date/TimeEdit     日期/时间编辑框"))
        self.pushButton_30.setText(_translate("MainWindow", "ComboBox     不可编辑组合框  "))
        self.pushButton_36.setText(_translate("MainWindow", "TextEdit     文本编辑"))
        self.pushButton_38.setText(_translate("MainWindow", "PlainTextEdit     无格式的文本编辑 "))
        self.pushButton_32.setText(_translate("MainWindow", "FontComboBox     可编辑组合框"))
        self.pushButton_40.setText(_translate("MainWindow", "SpinBox     整数旋转框 "))
        self.pushButton_43.setText(_translate("MainWindow", "Vertical Slider     垂直滑动条"))
        self.pushButton_31.setText(_translate("MainWindow", "DateEdit     日期编辑框"))
        self.pushButton_35.setText(_translate("MainWindow", "Dial     表盘"))
        self.pushButton_44.setText(_translate("MainWindow", "TimeEdit     时间编辑框"))
        self.pushButton_39.setText(_translate("MainWindow", "Vertical ScrollBar     垂直滚动条"))
        self.pushButton_41.setText(_translate("MainWindow", "Horizontal Slider     水平滑动条"))
        self.pushButton_45.setText(_translate("MainWindow", "key Sequence Edit键序列编辑"))
        self.pushButton_34.setText(_translate("MainWindow", "LineEdit     行编辑"))
        self.label_8.setText(_translate("MainWindow", "显示组件Display Widgets"))
        self.commandLinkButton_3.setText(_translate("MainWindow", "显示组件精讲网址"))
        self.pushButton_51.setText(_translate("MainWindow", "ProgressBar     进度条"))
        self.pushButton_46.setText(_translate("MainWindow", " Label     标签"))
        self.pushButton_47.setText(_translate("MainWindow", "TextBrowser     文本浏览器"))
        self.pushButton_50.setText(_translate("MainWindow", "LCDNumber     LCD数字显示框"))
        self.pushButton_49.setText(_translate("MainWindow", "Calendar     日历控件"))
        self.pushButton_54.setText(_translate("MainWindow", "OpenGL Widget OpenGL窗口小部件"))
        self.pushButton_52.setText(_translate("MainWindow", " HorizontalLine     水平线条"))
        self.pushButton_48.setText(_translate("MainWindow", "GraphicsView     绘图视图  "))
        self.pushButton_53.setText(_translate("MainWindow", "VerticalLine     垂直线条"))
        self.menu.setTitle(_translate("MainWindow", "介绍"))
        self.actionjdl.setText(_translate("MainWindow", "帮助"))
        self.actionlianxi.setText(_translate("MainWindow", "联系"))
import A_rc
import Q_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
